"""add date_created at User table

Revision ID: 3d29e065a3f1
Revises: 7a9ae2f7bfe2
Create Date: 2022-10-30 07:44:02.013489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d29e065a3f1'
down_revision = '7a9ae2f7bfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
